app:
  log:
    home: /Users/gaoxi/logs
  app:
    name: qt-asia

server:
  port: 8080

spring.datasource:
  address: 127.0.0.1:3306
  database: qt_asia
  username: root
  password: 123456
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://${spring.datasource.address}/${spring.datasource.database}?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  hikari:
    maximum-pool-size: 30
    minimum-idle: 1
